nav:
  Contact: /#contact
  Profile: /#profile
  Education: /#education
  Teaching: /#teaching
  Work: /#work
  Exhibitions: /#exhibitions
  Awards: /#awards
  Talks: /#talks
  Press: /#press
  # these can be whatever you like
  # but they must match your div ids!

projects_url: http://github.com/olliepalmer

customize:
    gravatar:
        email:
    logo:
        enabled: false
        width: 50
        height: 50
        url: /images/logo.png
        gravatar: false
    favicon:
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.ico
        gravatar: false
      android:
        url: /images/favicon-192x192.png
        gravator: false
      apple:
        url: /images/apple-touch-icon.png
        gravator: false
    social_links:
        github: http://github.com/olliepalmer
        twitter: https://twitter.com/_olliepalmer
    show_all_posts: true
    post_count: 100
    highlight: monokai

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: UA-1963104-15 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
